---

plugins: [flowtype]

env:
  node: true
  jest: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb/base'
  - plugin:import/errors
  - plugin:import/warnings
